export const translation = {
  Türkmen: {
    welcome: 'Salam!',
    category: 'Kategoriýalar',
    main: 'Baş sahypa',
    fruits: 'Gök önümler we miweler',
    all: 'Ähli bildirişler',
    new: 'Täze goşulanlar',
    profil: 'Meniň Profilim',
    add: 'Bildiriş goşmak', 
    my_product: 'Meniň bildirişlerim',
    favourite: 'Halanlarym',
    clock: '9.00 dan 18.00 çenli',
    about: 'Biz barada',
    how_use: 'Nädip ulanmaly',
    use_text: 'Okap tanyş',
    rule_text: 'Ulanyş düzgünleri',
    rule: 'Maglumat goýmak düzgünleri',
    question: 'Sorag-jogap',
    services: 'Hyzmatlar',
    tel: 'Telefon belgiňiz',
    password: 'Password',
    choose_category: 'Kategoriýa saýlaň ',
    choose_place: 'Ýeri saýlaň',
    deliveri: 'Eltip berme',
    credit: 'Kredit',
    yes: 'Bar',
    place: 'Ýeri',
    pay: 'Töleg',
    arassala: 'Aassala',
    ctg: 'Kategoriýa',
    habarlashmak: 'Habarlaşmak üçin',
    giňişleýin: 'Giňişleýin',
    cost: 'Bahasy',
    amount: 'Möçberi',
    call: 'Jaň etmek',
    addFavourite: 'Halanlaryma goş',
    description: 'Düşündiriş',
    cardInform: 'Sizde öňden goşulan haryt tapylmady',
    name: 'Ady',
    cardDescription: 'Giňişleýin maglumat bermek',
    choose_img: 'Surat saýlaň',
    add_img: 'Köpräk surat goşmak',
    addBtn: 'Goşmak',
    search: 'Gözle...',
    notFound: 'Gözlenilýan sahypa tapylmady',
    notFound2: 'Baş sahypa geçmek'
  },
  Русский: {
    welcome: 'Привет!',
    category: 'Категорые',
    main: 'Главная',
    fruits: 'Овощи и фрукты', 
    all: 'Все продукты',
    new: 'Новые продукты',
    profil: 'Мой профиль',
    add: 'Добавить объявление', 
    my_product: 'Мои объявление',
    favourite: 'Фаворит',
    clock: 'от 9.00 до 18.00',
    about: 'О нас',
    how_use: 'Как использовть',
    use_text: 'Okap tanysh',
    rule_text: 'Rule',
    rule: 'How to add product',
    question: 'Вопросы и ответы',
    services: 'Службы',
    tel: 'Номер телефона',
    password: 'Пароль',
    choose_category: 'Выбирай категория',
    choose_place: 'Выбирай место',
    deliveri: 'Доставка',
    credit: 'Кредить',
    yes: 'Да',
    place: 'Место',
    pay: 'Плата',
    arassala: 'Очистить',
    ctg: 'Категория', 
    habarlashmak: 'О связь',
    giňişleýin: 'Подробно',
    cost: 'Цена',
    amount: 'Количество',
    call: 'Звонить',
    addFavourite: 'Добавить фаворить',
    description: 'Объяснение',
    cardInform: 'У вaс нет никаких добавленные',
    name: 'Имя',
    cardDescription: 'Польное объяснение',
    choose_img: 'Выбирй фото',
    add_img: 'Добавить фото',
    addBtn: 'Добавить',
    search: 'Поиск...',
    notFound: 'Такого страница не сущесвуеть',
    notFound2: 'Перейти главного страница'
  }
}